### ISSUE TITLE
Doesn't work denops shared server(systemd)

### ISSUE THREAD

**Issue by skanehira** [skanehira/denops-silicon.vim#2]
systemd unit

```
[Unit]
Description=shared deno server of denops.vim

[Service]
Type=simple
ExecStart=/usr/bin/deno run -A --unstable --no-check %h/.cache/dein/repos/github.com/vim-denops/denops.vim/denops/@denops-private/cli.ts
Restart=always

[Install]
WantedBy=default.target
```

log

```
             └─38802 /usr/bin/deno run -A --no-check --unstable /home/yasunori/.cache/dein/repos/github.com/vim-denops/denops.vim/denops/@denops-private/cli.ts

 9月 04 00:40:46 yasunori-desktop deno[38802]: 127.0.0.1:36742 (Neovim) is closed
 9月 04 00:40:46 yasunori-desktop deno[38802]: SessionClosedError: The session is closed
 9月 04 00:40:46 yasunori-desktop deno[38802]:     at Session.close (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:179:31)
 9月 04 00:40:46 yasunori-desktop deno[38802]:     at Session.dispose (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:171:10)
 9月 04 00:40:46 yasunori-desktop deno[38802]:     at Service.dispose (file:///home/yasunori/.cache/dein/repos/github.com/vim-denops/denops.vim/denops/@denops-private/service.ts:129:22)
 9月 04 00:40:46 yasunori-desktop deno[38802]:     at using (https://deno.land/x/disposable@v1.0.2/using.ts:16:20)
 9月 04 00:40:46 yasunori-desktop deno[38802]:     at async file:///home/yasunori/.cache/dein/repos/github.com/vim-denops/denops.vim/denops/@denops-private/cli.ts:66:5
 9月 04 00:40:46 yasunori-desktop deno[38802]:     at async using (https://deno.land/x/disposable@v1.0.2/using.ts:14:12)
 9月 04 00:40:52 yasunori-desktop deno[38802]: 127.0.0.1:36746 (Neovim) is connected
 9月 04 00:41:07 yasunori-desktop deno[38802]: 127.0.0.1:36746 (Neovim) is closed
```

**Comment by skanehira** [comment]
Cannot reproduced
